# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7a15tftg256-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Vivado/processor/processor.cache/wt [current_project]
set_property parent.project_path C:/Vivado/processor/processor.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Vivado/processor/processor.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  C:/Vivado/processor/processor.srcs/sources_1/new/ALU.sv
  C:/Vivado/processor/processor.srcs/sources_1/new/Datapath.sv
  C:/Vivado/processor/processor.srcs/sources_1/new/controller.sv
  {C:/Vivado/processor/processor.srcs/sources_1/new/data memory.sv}
  C:/Vivado/processor/processor.srcs/sources_1/new/digits.sv
  {C:/Vivado/processor/processor.srcs/sources_1/new/instruction memory.sv}
  {C:/Vivado/processor/processor.srcs/sources_1/new/register file.sv}
  {C:/Vivado/processor/processor.srcs/sources_1/new/sign extend.sv}
  C:/Vivado/processor/processor.srcs/sources_1/new/processor.sv
}
read_ip -quiet C:/Vivado/processor/processor.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all c:/Vivado/processor/processor.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Vivado/processor/processor.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all c:/Vivado/processor/processor.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Vivado/processor/processor.srcs/constrs_1/new/ports.xdc
set_property used_in_implementation false [get_files C:/Vivado/processor/processor.srcs/constrs_1/new/ports.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Processor16 -part xc7a15tftg256-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Processor16.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Processor16_utilization_synth.rpt -pb Processor16_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
